# Generated by Django 2.2.10 on 2020-02-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastmile', '0002_auto_20200221_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='update',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
