# Generated by Django 2.2.10 on 2020-02-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastmile', '0003_auto_20200224_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='status_description',
            field=models.TextField(blank=True),
        ),
    ]
