# Generated by Django 2.2.10 on 2020-02-25 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lastmile', '0005_commitment_status_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lastmile.Agreement')),
            ],
        ),
        migrations.AddField(
            model_name='commitment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lastmile.CommitmentCategory'),
        ),
    ]
