# Generated by Django 2.2.10 on 2020-02-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastmile', '0006_auto_20200225_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitment',
            name='achieved_number',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='target_number',
        ),
        migrations.RemoveField(
            model_name='update',
            name='achieved_number',
        ),
        migrations.AddField(
            model_name='commitment',
            name='goal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='commitment',
            name='progress_toward_goal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='commitmentcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='update',
            name='progress_toward_goal',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
