# Generated by Django 3.0.5 on 2020-04-10 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lastmile', '0007_auto_20200225_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='responsible_parties',
            field=models.ManyToManyField(blank=True, to='lastmile.Actor'),
        ),
        migrations.AlterField(
            model_name='action',
            name='responsible_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deprecated', to='lastmile.Actor'),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('pending', 'Not Started'), ('active', 'Active'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='status',
            field=models.CharField(choices=[('pending', 'Not Started'), ('active', 'Active'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=100),
        ),
    ]
