# Generated by Django 3.0.5 on 2020-05-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastmile', '0010_auto_20200422_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
