# Generated by Django 3.0.5 on 2020-05-06 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lastmile', '0011_attachment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lastmile.Attachment'),
        ),
    ]
