# Generated by Django 3.0.5 on 2020-05-12 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lastmile', '0012_update_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='attachment',
        ),
    ]
