# Generated by Django 3.0.5 on 2020-05-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastmile', '0015_agreement_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='agreement',
            field=models.ManyToManyField(blank=True, to='lastmile.Agreement'),
        ),
    ]
