# Generated by Django 3.0.5 on 2020-06-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lastmile', '0016_actor_agreement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commitmentcategory',
            options={'verbose_name_plural': 'commitment categories'},
        ),
    ]
