# Generated by Django 3.0.5 on 2020-06-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastmile', '0017_auto_20200622_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('pending', 'Not Started'), ('active', 'Active'), ('complete', 'Complete'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='pending', max_length=100),
        ),
    ]
