# Generated by Django 3.0.5 on 2020-06-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastmile', '0018_auto_20200623_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='status',
            field=models.CharField(choices=[('pending', 'Not Started'), ('active', 'Active'), ('complete', 'Complete'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='pending', max_length=100),
        ),
    ]
