# Generated by Django 3.0.5 on 2020-06-30 20:38

from django.db import migrations, models
import django.db.models.deletion
import django_lastmile.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('lastmile', '0019_auto_20200629_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('hero_video', models.CharField(blank=True, max_length=255)),
                ('hero_image', models.ImageField(blank=True, null=True, storage=django_lastmile.storage_backends.PrivateMediaStorage(), upload_to='images/')),
                ('story_image', models.ImageField(blank=True, null=True, storage=django_lastmile.storage_backends.PrivateMediaStorage(), upload_to='images/')),
                ('story_part1', models.TextField(blank=True)),
                ('story_part2', models.TextField(blank=True)),
                ('story_part3', models.TextField(blank=True)),
                ('achievements_text', models.TextField(blank=True)),
                ('challenges_text', models.TextField(blank=True)),
                ('commitment_chart_text', models.TextField(blank=True)),
                ('commitments_image', models.ImageField(blank=True, null=True, storage=django_lastmile.storage_backends.PrivateMediaStorage(), upload_to='images/')),
                ('about_us', models.TextField(blank=True)),
                ('methodology', models.TextField(blank=True)),
                ('report_name', models.CharField(blank=True, max_length=255)),
                ('report', models.URLField(blank=True, max_length=255)),
                ('case_page', models.URLField(blank=True, max_length=255)),
                ('agreement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lastmile.Agreement')),
            ],
        ),
        migrations.AlterModelOptions(
            name='commitment',
            options={'ordering': ('order_num',)},
        ),
        migrations.AlterModelOptions(
            name='commitmentcategory',
            options={'ordering': ('order_num',), 'verbose_name_plural': 'commitment categories'},
        ),
        migrations.AddField(
            model_name='commitment',
            name='order_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commitmentcategory',
            name='order_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, storage=django_lastmile.storage_backends.PrivateMediaStorage(), upload_to='images/')),
                ('order_id', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('commitments', models.ManyToManyField(blank=True, to='lastmile.Commitment')),
                ('overview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lastmile.Overview')),
            ],
            options={
                'ordering': ('order_id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, storage=django_lastmile.storage_backends.PrivateMediaStorage(), upload_to='images/')),
                ('order_id', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('commitments', models.ManyToManyField(blank=True, to='lastmile.Commitment')),
                ('overview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lastmile.Overview')),
            ],
            options={
                'ordering': ('order_id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, storage=django_lastmile.storage_backends.PrivateMediaStorage(), upload_to='images/')),
                ('order_id', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('commitments', models.ManyToManyField(blank=True, to='lastmile.Commitment')),
                ('overview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lastmile.Overview')),
            ],
            options={
                'ordering': ('order_id',),
                'abstract': False,
            },
        ),
    ]
