# Generated by Django 3.0.5 on 2020-08-17 20:52

from django.db import migrations, models
import django.db.models.deletion
import django_lastmile.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('lastmile', '0020_auto_20200630_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(blank=True, null=True, storage=django_lastmile.storage_backends.PrivateMediaStorage(), upload_to='docs/')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('overview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lastmile.Overview')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
