# Generated by Django 3.0.5 on 2020-08-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastmile', '0021_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='highlight_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='special_text_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
