# Generated by Django 3.0.5 on 2020-08-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastmile', '0022_auto_20200817_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='bg_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='bg_color_2',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='bg_color_3',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
