# Generated by Django 3.0.5 on 2020-08-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lastmile', '0023_auto_20200817_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commitment',
            options={'ordering': ('category', 'order_num')},
        ),
    ]
